# Faktoryzacja QR
Laboratorium 11 - Metody Obliczeniowe w Nauce i Technice

In [3]:
import numpy as np
import os
import matplotlib.pyplot as plt
import time

## Zadanie 1. Faktoryzacja QR metodą Grama-Schmidta.

### 1.

In [44]:
def qr(A: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    n = A.shape[0]
    # print(A[:, 0], np.linalg.norm(A[:, 0]))

    # Q
    # for k in range(1, n):
    #     a = A[:, k].copy()
    #     ak = A[:, k].copy()
    #     for i in range(k):
    #         ui = Q[:, i].copy()
    #         ak -= ui @ a * ui
    #     uk = ak / np.linalg.norm(ak)
    #     Q = np.column_stack((Q, uk))

    # Q
    Q = np.empty((n, n))
    Q[:, 0] = A[:, 0] / np.linalg.norm(A[:, 0])
    for k in range(1, n):
        ak = A[:, k]
        _sum = np.zeros((1, n))
        for i in range(k):
            ui = Q[:, i]
            _sum += ui @ ak * ui
            print(f"k {k}, i {i}", ui @ ak * ui)


        Q[:, k] = A[:, k] - _sum
        Q[:, k] /= np.linalg.norm(Q[:, k])

    # R
    R = np.zeros((n, n))
    for i in range(n):
        for j in range(i, n):
            R[i, j] = Q[:, i] @ A[:, j]

    return Q, R


print(qr(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.float64))[0])
print(np.linalg.qr(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.float64))[0])

k 1, i 0 [1.18181818 4.72727273 8.27272727]
k 2, i 0 [1.36363636 5.45454545 9.54545455]
k 2, i 1 [ 1.63636364  0.54545455 -0.54545455]
[[ 0.12309149  0.90453403 -0.92060161]
 [ 0.49236596  0.30151134 -0.32491822]
 [ 0.86164044 -0.30151134  0.21661214]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]


### 2.

In [34]:
def test_correctness():
    for n in [16, 32, 100, 500, 1024]:
        A = np.random.rand(n , n) * np.random.rand() * 100
        Q, R = qr(A)
        np_Q, np_R = np.linalg.qr(A)
        print(f"Dla n = {n}: {np.allclose(Q, np_Q) and np.allclose(R, np_R)}")


test_correctness()

Dla n = 16: False
Dla n = 32: False
Dla n = 100: False
Dla n = 500: False
Dla n = 1024: False


### 3.

### 4.

### 5.